### ISSUE TITLE
NOT_ADS_USER

### ISSUE THREAD

**Issue by pratikanay16** [google/shopping-markup#3]
Hi,

We follow all things to set up a service account and delegate to google workspace. Even though we have the same error.  Error concern because of the service account used to access google Ads account and that have no permission. Can you advise how to solve it in your script? Do we get requests and responses log?

**Comment by prithvinambiar** [comment]
@pratikanay16 - You will have to use the end user credentials for this solution. Make sure the user who is running the installation has access to both Google Ads and GMC account (standard access).

**Comment by pratikanay16** [comment]
Installation asking to create a service account. After that service account tries to access the Gads/GMC account.
E.g I have gcloud/Google workspace account is workspace@xyz.com. workspace@xyz.com have access of GAds/GMC/GCP.
Installation asking to create a service account. So we create it inside GCP using workspace@xyz.com. Once we create a service account we configure JSON file in an environment variable. service account email id like markup@markup-xxxxxx.iam.gserviceaccount.com. This email id has no access to Google ADS and we can not give access to this email id as asking to verify it. In GMC we can add this email id so it's work.
